version: '3'

services:
  

  izing-redis:
    container_name: "redis"
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env
    volumes:
      - '$HOME/www/izing/database/redis:/data'
    
  izing-rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: always
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # healthcheck:
    #   test: [ "CMD", "nc", "-z", "localhost", "5672" ]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    volumes:
      - $HOME/www/izing/database/rabbitmq/data/:/var/lib/rabbitmq/
      - $HOME/www/izing/database/rabbitmq/logs/:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
   
  izing-backend:
    container_name: "izing-backend"
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3100:3100
      - 3000:3000
    # command: /start_production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./backend:/usr/src/app"
      - $HOME/www/izing/media:/usr/src/app/public
  
    depends_on:
      - izing-redis
      - izing-rabbitmq
  
  izing-frontend:
    container_name: izing-frontend
    build:
      context: .
      # args:
      #   - DOMINIO_CLIENTE=${DOMINIO_CLIENTE}
    restart: always
    stdin_open: true
    tty: true
    entrypoint: nginx -g "daemon off;"
    ports:
      
      - "8080:8080"
    volumes:
      - $HOME/www/izing/media:/opt/services/app/media
    depends_on:
      - izing-backend
   

